services:
  app:
    image: vohuan0404/medimateserver:v1.0
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=medimateserver
    depends_on:
      - db

  db:
    image: vohuan0404/medimateserver-mysql-database:v1.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: medimateserver
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
